site_name: "Documentation | DAB"
site_author: dab.ooo
site_description: All the data an IC app needs to make seamless experiences, accessible directly on the IC. Canister, NFT, Token, and Dapp registries/lists
site_url: https://docs.plugwallet.ooo/
copyright: 'Â© 2021 Built by Fleek'
repo_name: psychedelic/dab
repo_url: https://github.com/psychedelic/dab
theme:
  name: material
  custom_dir: overrides
  favicon: './imgs/favicon.ico'
  logo: './imgs/logo.png'
  font:
    text: 'Open Sans'
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/codehilite-theme.css'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: true
nav:
  - Welcome to DAB ğŸ‘‹: index.md
  - <b>Developer Guides</b> ğŸ§°: "#"
  - Getting Started: getting-started/connect-to-plug/#browser-extension
  - Connect apps to Plug: getting-started/connect-to-plug/#requestconnectrequestconnectparams
  - Using the PlugAgent: getting-started/connect-to-plug/#plug-agent-agent
  - <b>Build an App Examples</b> ğŸ’¡: "#"
  - Buy me a Coffee: build-an-app-examples/build-app-buy-me-a-coffee.md
  - Plugged (E2E): build-an-app-examples/build-app-plugged.md
  - NNS Stats: build-an-app-examples/plug-auth-nns.md
  - Coinflip: "https://2ji5m-raaaa-aaaah-aanoa-cai.raw.ic0.app"  
  - <b>Resources</b> ğŸ“š:
    - Resource Library: resources/library.md
    - Depositing Cycles: resources/buying-cycles.md
    - Recovering Sub-accounts: resources/multiple-accounts.md    
    - Migrating Curves: resources/migrating-curve.md
    - Common Terms: common-terms/plug-dictionary.md  
    - The Internet Computer: "https://dfinity.org/faq"
    - Disclaimer: resources/disclaimer.md
    - Trademark: resources/trademark.md
    - Privacy: resources/privacy.md
    - Our App Ecosystem ğŸŒ€: resources/apps-with-plug.md
  - <b>FAQs</b> â“: resources/faq.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/psychedelic/plug/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/plug_wallet
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yVEcEzmrgm