site_name: "Documentation | DAB"
site_author: dab.ooo
site_description: All the data an IC app needs to make seamless experiences, accessible directly on the IC. Canister, NFT, Token, and Dapp registries & lists.
site_url: https://docs.dab.ooo/
copyright: 'Â© 2021 Built by Fleek LLC'
repo_name: psychedelic/dab
repo_url: https://github.com/psychedelic/dab
theme:
  name: material
  custom_dir: overrides
  favicon: './imgs/favicon.ico'
  logo: './imgs/logo.png'
  font:
    text: 'Open Sans'
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/codehilite-theme.css'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: true
nav:
  - Welcome to DAB ğŸ‘‹: index.md
  - <b>The NFT List</b> ğŸ¨: "#"
  - Getting Started: nft-list/getting-started.md
  - Fetching a User's NFTs: nft-list/getting-started/#2-fetching-all-nfts-the-user-owns-getallusernfts
  - Interacting with NFTs: nft-list/getting-started/#3-interacting-with-nfts-using-nftactor-getusertokens-transfer-details
  - Current NFT List: "https://github.com/Psychedelic/dab/blob/main/registries/nft/list.json"
  - Submit an NFT: "https://dab-ooo.typeform.com/nft-list"  
  - <b>The Canister List</b> ğŸ›¢ï¸: "#"
  - Getting Started: canister-list/getting-started.md
  - Single-canister Query: canister-list/getting-started/#2-check-a-single-canisters-metadata-in-the-registry-getcanisterinfo
  - Multi-canister Query: canister-list/getting-started/#3-check-multiple-canisters-metadata-in-the-registry-getmultiplecanisterinfo
  - Current List: "https://github.com/Psychedelic/dab/blob/main/registries/canister_registry/list.md"
  - Submit a Canister: "https://dab-ooo.typeform.com/canister-list"    
  - <b>Developer Tools</b> ğŸ’¡: "#"
  - DAB-JS Library: https://github.com/Psychedelic/DAB-js/
  - Main DAB Repo: https://github.com/Psychedelic/DAB/
  - <b>Resources</b> ğŸ“š:
    - The Internet Computer: "https://dfinity.org/faq"
    - Disclaimer: resources/disclaimer.md
    - Trademark: resources/trademark.md
    - Privacy: resources/privacy.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/psychedelic/dab/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dab_ooo
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yVEcEzmrgm